name: build

on:
  push:
    branches-ignore:
      - 'release*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 14
       uses: actions/setup-java@v1
       with:
         java-version: 1.14
     - name: Build with Maven
       run: mvn clean compile install -DskipTests --file pom.xml
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14
      - name: Run unit tests
        run: mvn test --file pom.xml
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14
      - name: Maven Package
        run: mvn -B clean package -DskipTests
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.14
      - name: Maven Verify
        run: mvn -B clean verify

